# Generated by Django 4.1.3 on 2022-12-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alocada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaga', models.CharField(max_length=2, verbose_name='Nº vaga')),
                ('placa', models.CharField(max_length=9, verbose_name='Placa')),
                ('modelo', models.CharField(max_length=15, verbose_name='Modelo')),
            ],
        ),
        migrations.CreateModel(
            name='Vazia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaga', models.CharField(max_length=2, verbose_name='Nº vaga')),
                ('placa', models.CharField(max_length=9, verbose_name='Placa')),
                ('modelo', models.CharField(max_length=15, verbose_name='Modelo')),
            ],
        ),
    ]
